### ISSUE TITLE
Improve compatibility checking for CurseForge mods

### ISSUE THREAD

**Issue by tastesliketriangle** [theRookieCoder/ferium#12]
[JEI](https://www.curseforge.com/minecraft/mc-mods/jei) fails to install for version 1.12.2, despite having several versions of the mod for that version.

error:
`Downloading Just Enough Items (JEI)
  [1] Getting file information... × No version of Just Enough Items (JEI) is compatible for Forge 1.12.2`

[Cosmetic Armor](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked) failed in the same way. For comparison [Botania](https://www.curseforge.com/minecraft/mc-mods/botania) downloaded fine, and [LootTweaker](https://www.curseforge.com/minecraft/mc-mods/loottweaker) downloaded with the "old parser."

The only difference I can see is that Botania explicitly has `forge` as a supported modloader, and LootTweaker has `1.12` as a supported version tag. Maybe a bug in the "old parser?"

**Comment by theRookieCoder** [comment]
I checked JEI's 1.12.2 versions and it seems that they don't tag `Forge` as a compatible game version (they do for newer versions). I really dislike CF's system of specifying compatible mod loaders and game versions as problems like this can occure quite frequently. Same problem with Cometic Armour they don't specify the mod loader in 1.12.2, again they _do_ for the newer versions though. It's understandable I guess since Forge was basically the only mod loader for 1.12.2

**Comment by theRookieCoder** [comment]
I'm planning on adding overrides for specific mods in the config. For example in this case you could enable a 'bypass mod loader check' or something

**Comment by theRookieCoder** [comment]
Fixed in 0475f7c6683d21bfc33ae8816cbcf8288e5b5193
For this specific issue, I'd disable the mod loader check
