### ISSUE TITLE
Add support for only downloading file that need to be updated

### ISSUE THREAD

**Issue by KyleUltimate** [theRookieCoder/ferium#14]
For example, I have three mods downloaded:

1. Sodium
2. Iris
3. DashLoader

But only DashLoader needs to be updated. Ferium should only update dashloader and keep other mods intact.

**Comment by theRookieCoder** [comment]
Yes this is something that needs to be worked on

**Comment by KyleUltimate** [comment]
Also I have a question about how will this be implemented.
I currently have iris that is compiled from source, how would ferium know my iris jar is "newer" than the modrinth/curseforge, would it just throw and error if the jar doesn't follow semver?

**Comment by theRookieCoder** [comment]
The only real proper way to do this would be to extract the mod, check the mod version in the `fabric.mod.json` (and whatever the forge equivalent is), and check if it's the same or newer than the version that was picked by Ferium. But this defeats the whole purpose because I guarantee you this takes longer than just downloading the latest file.

Another method would be to check the file name, and if it matches with the version that was picked by Ferium, then don't download the file. I'm testing this right now.

A third method would be to use an api call that gets the version of a file based on its hash. So, you hash the mod file, send that to the API, and the API will tell you the version of the file (if they have it). But this functionality is currently only offered by Modrinth.

**Comment by theRookieCoder** [comment]
Fixed by ca6bcb70733625079e8c01665adf6e215f9819fe. Although actually checking what the latest version is still takes a long time because of all the API calls
