### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by cootshk** [theRookieCoder/ferium#18]
how do I install this? (Windows 10, x64)

**Comment by theRookieCoder** [comment]
1. Download the `windows-msvc` zip file of the [latest release](https://github.com/theRookieCoder/ferium/releases/latest)
2. Unzip the zip file, you should get `ferium.exe`
3. Create a folder called `bin` in your home folder (the one with your username)
4. Follow [this guide](https://gist.github.com/nex3/c395b2f8fd4b02068be37c961301caa7#windows) to add this binary folder to your `PATH` so that your computer know to look there for Ferium

I hope you are comfortable with the command line, because you might not know how to use Ferium if you don't. I recommend something like [PolyMC](https://polymc.org/) if you want a GUI

**Comment by KyleUltimate** [comment]
Maybe add using `setx` for PATH setting in the README too?

**Comment by theRookieCoder** [comment]
It seem that `setx` doesn't allow you to change the user path, it ends up combining both system and user paths. I just searchef this up and `pathman` seems to work properly. I'll test it tomorrow and add it if it works. Thank you for the suggestion!
