### ISSUE TITLE
Only use Fabric backward compatibility when a Quilt version can not be found

### ISSUE THREAD

**Issue by KyleUltimate** [theRookieCoder/ferium#30]
Such as blur(fabric). The newest does support fabric and quilt in the same jar, but ferium says its a fabric mod.
But mods such as qsl and ok Zoomer, which both states that the only loader allows, ferium does determine it as a quilt mod successfully.
Iris on the other hand has another problem
1.2.3 does support quilt, but the newest 1.2.4 only supports fabric(But works in quilt)
Ferium currently downloads 1.2.4, but technically it should download 1.2.3 instead
(The iris problem is fixed, IMS updated that iris supports quilt too, but this still could be a problem)

**Comment by theRookieCoder** [comment]
As for your problem with Blur, I'm unable to replicate it. When I upgrade with Blur, I get a green tick which means the mod downloaded is specified as compatible with Quilt. The second problem with Iris can be fixed by only relying on Fabric backwards compatibility when the mod can't find a Quilt version.

**Comment by KyleUltimate** [comment]
Oh wait I found the problem. I added blur as curseforge instead of modrinth, that's why it can't find it!
Sorry for the inconvenience!

**Comment by theRookieCoder** [comment]
Wait but the Fabric version is still downloaded instead of the Quilt version, that's not expected behaviour so I'll open the issue again.

**Comment by theRookieCoder** [comment]
Fixed by 9d0f3b09d294b354d3b463526932684a2d004471
